### ISSUE TITLE
Add version information in composer.json

### ISSUE THREAD

**Issue by texnixe** [rasteiner/k3-trevor-view#17]
Currently, version information does not show up in system view due to missing information in composer.json

**Comment by rasteiner** [comment]
I always forget to update that in the file and then packagist refuses to update the package because of a "version mismatch". I think this will be a "wontfix".

**Comment by texnixe** [comment]
Hm, pretty annoying to keep track of versions without this information if you can't/don't want to use composer or git submodules.

**Comment by rasteiner** [comment]
Should be fixed in 0.2.1 :)

**Comment by texnixe** [comment]
Thank you for the quick fix!
