### ISSUE TITLE
Feature suggestion: option to avoid creating new keys in the Panel.

### ISSUE THREAD

**Issue by malvese** [rasteiner/k3-trevor-view#21]
I usually don't want users to create new strings. Because If they add new strings which are not already used in templates, they have no way to use or see them in the website, it is confusing.

**Comment by rasteiner** [comment]
I've added a config option:

```php
<?php
return [
    'trevor' => [
        'allow_add_keys' => false,
    ],
];
```

**Comment by malvese** [comment]
That was fast! Thank you very much :)
