### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by S1SYPHOS** [rasteiner/k3-trevor-view#3]
Hey there,
I'm trying to use Trevor with v3.2.5. Although it seems all language variables (as defined in `site/languages/[lang].php`) are detected, after selecting any of them, I get this:

```
this.$refs.keyspane[t].scrollIntoViewIfNeeded is not a function 
```

Any idea how to proceed / debug this?

Cheers,
S1SYPHOS

**Comment by mpatzner** [comment]
Here's your answer: https://caniuse.com/scrollintoviewifneeded
You need to polyfill this feature if using Firefox, for example.

**Comment by rasteiner** [comment]
just switched to `.scrollIntoView({block: "nearest"})`, which should be good enough. 
Didn't know scrollIntoViewIfNeeded isn't in firefox
